name: Bug Report
description: File a structured report to help us improve GhostNet.
title: "[Bug]: "
labels: ["bug", "new bug"]
body:
  - type: markdown
    attributes:
      value: |

        Before opening a new issue, make sure it isn't covered by an existing issue.
        Please search for [issues with the `new bug` label](https://github.com/nothingbuttyler/ghostnet/issues?q=is%3Aissue+label%3A%22new+bug%22)
        (including closed issues) before you continue. If you find one for the brand
        you're requesting then leave a comment on it or add a reaction.

        > [!TIP]
        > Before opening a new issue, make sure it isn't covered by an existing issue.
        >  Please search for [issues with the `new bug` label](https://github.com/nothingbuttyler/ghostnet/issues?q=is%3Aissue+label%3A%22new+bug%22)

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Tell us how to see the bug ourselves.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where are you running the bot?
      options:
        - Windows
        - Linux (Ubuntu/Debian)
        - MacOS
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Additional Comments
      description: |
        Is there anything else we should know about the bug?
      placeholder: 'Example: There are multiple ways to activate...'

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have checked to see if there have been any updates within 5 hours.
          required: true
